# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start from the official Node.js image
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install the project's dependencies
RUN npm install --ignore-scripts

# Copy the rest of the project files
COPY . .

# Build the TypeScript files
RUN npm run build

# Use a lighter image for the release
FROM node:18-alpine AS release

# Set working directory
WORKDIR /app

# Copy the build from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install only production dependencies
RUN npm install --omit=dev

# Set environment variables
ENV KEYCLOAK_URL=http://localhost:8080
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin

# Command to run the application
ENTRYPOINT ["node", "dist/index.js"]